### ISSUE TITLE
[Training code]

### ISSUE THREAD

**Issue by tomguluson92** [lyx0208/3dSwap#2]
Hi!
Glad to see 3dSwap publicly available to the community! I check the **training** directory and found nothing related to the actual training of 3dSwap.

I am wondering if your authors are willing to open-source the training code or not? Thanks!

**Comment by lyx0208** [comment]
Thanks for your issue! I'm preparing for the training code currently, and I believe it will be online late this week or early next week.

**Comment by lyx0208** [comment]
By the way, the "training" folder is from EG3D, containing its models such as the Triplane model.

**Comment by tomguluson92** [comment]
> Thanks for your issue! I'm preparing for the training code currently, and I believe it will be online late this week or early next week.

Looking forward to it

**Comment by tomguluson92** [comment]
@lyx0208 Thanks for the training code, but I have found that `options\train_options.py` is missing, could you please upload it at your convenience? Thank you very much!
