### ISSUE TITLE
Can you share the pretrained weights on Google Drive?

### ISSUE THREAD

**Issue by cloneisme** [lyx0208/3dSwap#4]
Thank you for showcasing your incredible work!

Your idea in this paper is truly interesting.

Would it be possible for you to share the pretrained weights on Google Drive as well?

Many researchers would be grateful for your contribution.

**Comment by lyx0208** [comment]
Of course! I will upload it to Google Drive and update the README soon.
However, currently I can only upload the preprocessed datasets (CelebA-HD and FFHQ) to Baidu disk due to the storage limitation of Google Drive.

**Comment by lyx0208** [comment]
Done.

**Comment by cloneisme** [comment]
Wow! You are the best. Thank you for generously sharing your excellent work with us.
