### ISSUE TITLE
[Encoder][Irregular blue eyes]

### ISSUE THREAD

**Issue by tomguluson92** [lyx0208/3dSwap#6]
Hi authors,

When I train the Encoder with tons of attempts, I have found there exists abnormal blue eye effects and seems the entanglement between `ws` and `camera_pose (cp)` is somewhat serious, so it is hard to be ensure a consistent `w` latent space.

To address this, I replace the default StyleGAN superresolution network with fixed GFPGAN, if you are interested in improving your work, we can have some discussions

> Newest edition **Encoder** (Face ID higher, bad multi-view consistency)

![image](https://github.com/lyx0208/3dSwap/assets/19585240/b9794fcf-9b22-4a28-8d6f-ddcee4761655)
![image](https://github.com/lyx0208/3dSwap/assets/19585240/7702ba62-6436-4a20-941c-fb4b2f9305cc)

> Traditional edition **Encoder** (Face ID lower, good multi-view consistency)

![image](https://github.com/lyx0208/3dSwap/assets/19585240/2599bc75-aa74-4b51-b30b-11fd4f49be36)
![image](https://github.com/lyx0208/3dSwap/assets/19585240/2e8f60a9-fc80-4095-9449-a52a9ebb699f)

**Comment by lyx0208** [comment]
This seems abnormal as I haven't met such a problem during my training. 
Can you further provide some information about your data preprocessing process?
