### ISSUE TITLE
Testing with custom model checkpoints

### ISSUE THREAD

**Issue by takuphilchan** [lyx0208/3dSwap#8]
@lyx0208 Hi. May you please assist me with information on how we can test using the model checkpoints we get from training_faceswap.py, something similar to what we can do with run_3dswap.py . I tried to check the readme file but it doesn't address this part. Are there modification I that need to faceswap_coach or any other file? Any insight will be greatly appreciated. Thank you.

**Comment by lyx0208** [comment]
Hello!
I think just rename the checkpoint and everything will be fine.

**Comment by takuphilchan** [comment]
@lyx0208 Thanks for response, I checked the new state dictionary it has both encoder and mlp keys, so i need to use the same state dictionary and for both and just filter keys for mlps and encoder, right? and also I wanted to ask if decoder stays the same or it also requires modifications?

**Comment by lyx0208** [comment]
Right! I think the decoder stays the same.

**Comment by takuphilchan** [comment]
Okay, thank you.
